### Test root endpoint
GET http://localhost:7007/api/v1/


### Get all albums
GET http://localhost:7007/api/v1/albums
Accept: application/json

### Get by id
GET http://localhost:7007/api/v1/albums/1
Accept: application/json

### Create new album
POST http://localhost:7007/api/v1/albums
Content-Type: application/json

{
  "title": "After hours",
  "releaseDate": "2020-07-13",
  "name": "The Weeknd",
  "genre": {
    "data": [
      {
        "id": 1,
        "name": "R&B"
      }
    ]
  },
  "nb_Tracks": 22
}

### Update album by id
PUT http://localhost:7007/api/v1/albums/1
Content-Type: application/json

{
  "albumTitle": "Blinding lights",
  "genre": {
    "id": 1,
    "name": "Rap"
  },
  "releaseDate": "2020-07-13",
  "artistName": "MGK",
  "nbTracks": 22
}

### Delete album by id
DELETE http://localhost:7007/api/v1/albums/1


### Get all artists
GET http://localhost:7007/api/v1/artist
Accept: application/json


### Get all songs
GET http://localhost:7007/api/v1/songs
Accept: application/json

### GET by id
GET http://localhost:7007/api/v1/songs/1
Accept: application/json

### Create new song
POST http://localhost:7007/api/v1/songs
Content-Type: application/json

{
  "title": "The Eye Color Ballad",
  "duration": 242,
  "genre": "Unknown",
  "releaseDate": "2022-05-23",
  "artistId": 3,
  "albumId": null
}

### Update song by id
PUT http://localhost:7007/api/v1/songs/1
Content-Type: application/json

{
  "title": "The Eye Color Ballad",
  "duration": 242,
  "genre": "Unknown",
  "releaseDate": "2015-02-08",
  "artistId": 3,
  "albumId": null
}

### Delete song by id
DELETE http://localhost:7007/api/v1/songs/1