### Test root endpoint
GET http://localhost:7007/api/v1/


### Get all albums
GET http://localhost:7007/api/v1/albums
Accept: application/json

### Get by id
GET http://localhost:7007/api/v1/albums/1
Accept: application/json

### Create new album
POST http://localhost:7007/api/v1/albums
Content-Type: application/json

{
  "albumTitle": "Blinding lights",
  "genre": "Hip hip",
  "releaseDate": "2020-7-13"
}

### Update album by id
PUT http://localhost:7007/api/v1/albums/1
Content-Type: application/json

{
  "albumTitle": "Blinding lights",
  "genre": "Rap",
  "releaseDate": "2020-7-13"
}

### Delete album by id
DELETE http://localhost:7007/api/v1/albums/1


### Get all artists
GET http://localhost:7007/api/v1/artist
Accept: application/json


### Get all songs
GET http://localhost:7007/api/v1/songs
Accept: application/json